version: "3.9"

services:
  api:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    command: uvicorn app.main:app --host ${HOST:-0.0.0.0} --port ${PORT:-8000}
    volumes:
      - ./:/code
      - archives:/data/archives

  worker:
    build: .
    env_file: .env
    depends_on:
      - redis
    command: celery -A app.celery_app.celery_app worker --loglevel=${LOG_LEVEL:-INFO}
    volumes:
      - ./:/code
      - archives:/data/archives

  beat:
    build: .
    env_file: .env
    depends_on:
      - redis
    command: celery -A app.celery_app.celery_app beat --loglevel=${LOG_LEVEL:-INFO}
    volumes:
      - ./:/code
      - archives:/data/archives

  flower:
    image: mher/flower:latest
    environment:
      - CELERY_BROKER_URL=${REDIS_URL}
      - FLOWER_PORT=5555
    ports:
      - "5555:5555"
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

volumes:
  archives:
